.TH "GOOGLE" "1" "August 2015" "Version 20151016" "User Commands"
.SH NAME
google \- Google from command line
.SH SYNOPSIS
.B google
.RI [ OPTIONS ]
.I KEYWORDS...
.SH DESCRIPTION
.B google
is a command line tool for performing Google searches from the terminal.
.SH OPTIONS
.TP
.BI \-s " N"
Start at the
.I Nth
result.
.TP
.BI \-n " N"
Show
.I N
results.
.TP
.BI \-l " LANG"
Search for the language LANG, such as
.I fi
for Finnish.
.TP
.B \-j
Open the first result in a web browser.
.TP
.B \-C
Enable color output.
.TP
.BI \-t " dN"
Time limit search [e.g. d5: 5 days, w5: 5 weeks, m5: 5 months, y5: 5 years]
.SH ENVIRONMENT
.TP
.BI BROWSER
Overrides the default browser. For full details, see
.I http://docs.python.org/library/webbrowser.html
.SH AUTHOR
Written by Henri Hakkinen.
Modified by Arun Prakash Jana <engineerarun@gmail.com>
.SH REPORTING BUGS
Report bugs to
.I https://github.com/jarun/google-cli/issues
.SH COPYRIGHT
Copyright \(co 2008 Henri Hakkinen.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.PP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
