.TH "GOOGLE" "1" "October 2008" "Version 20081014" "User Commands"
.SH NAME
google \- Google from command line
.SH SYNOPSIS
.B google
.RI [ -o ]
.RI [ -s N ]
.RI [ -n N ]
.I KEYWORDS...
.SH DESCRIPTION
TO BE WRITTEN
.SH OPTIONS
.BI \-o
Open the first result in a web browser.
.BI \-s " N"
Start at
.I N'th
result.
.BI \-n " N"
Show
.I N
results.
.SH ENVIRONMENT
.BI BROWSER
Overrides the default browser. For full details, see
.I http://docs.python.org/library/webbrowser.html
.
.SH AUTHOR
Written by Henri Hakkinen.
.SH REPORTING BUGS
Report bugs to <henux@users.sourceforge.net>.
.SH COPYRIGHT
Copyright \(co 2008 Henri Hakkinen.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.PP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
