.TH "GOOGLE" "1" "October 2008" "Version 20081015" "User Commands"
.SH NAME
google \- Google from command line
.SH SYNOPSIS
.B google
.RI [ OPTIONS ]
.I KEYWORDS...
.SH DESCRIPTION
.B google
is a small tool which allows Google searches to be done from the command line.
.SH OPTIONS
.TP
.BI \-s " N"
Start at
.I N'th
result.
.TP
.BI \-n " N"
Show
.I N
results.
.TP
.BI \-l " LANG"
Search for the language LANG, such as
.I fi
for Finnish.
.TP
.B \-o
Open the first result in a web browser.
.SH ENVIRONMENT
.TP
.B \-C
Colorizes the output using ANSI escape codes.
.TP
.BI BROWSER
Overrides the default browser. For full details, see
.I http://docs.python.org/library/webbrowser.html
.
.SH AUTHOR
Written by Henri Hakkinen.
.SH REPORTING BUGS
Report bugs to <henux@users.sourceforge.net>.
.SH COPYRIGHT
Copyright \(co 2008 Henri Hakkinen.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.PP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
